# version: '3.1' #https://docs.docker.com/compose/compose-file/compose-versioning/

# volumes:
#   mongo_vol:
# networks:
#   mongo_net:
#     driver: bridge

# services:

#   app:
#     image: tscampos/rotten-potatoes:v3
#     build:
#      dockerfile: dockerfile
#      context: ./ 
#     depends_on:
#     - mongodb
#     networks:
#     - mongo_net
#     ports:
#     - 5000:5000

#   mongodb:
#     image: mongo
#     ports:
#     - 27017:27017
#     networks:
#     - mongo_net
#     volumes:
#     - mongo_vol:/data/db
#     environment:
#       MONGODB_DB: admin
#       MONGODB_HOST: mongodb
#       MONGODB_PORT: '27017'
#       MONGODB_USERNAME: mongouser
#       MONGODB_PASSWORD: mongopwd

#   mongo-express:
#     image: mongo-express
#     ports:
#      - 8081:8081
#     networks:
#      - mongo_net
#     depends_on:
#      - mongodb
#     environment:
#       ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
#       ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#       ME_CONFIG_MONGODB_AUTH_USERNAME: mongouser
#       ME_CONFIG_MONGODB_AUTH_PASSWORD: mondopwd
#       ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongodb:27017

# Use root/example as user/password credentials
version: '3.1'


services:

  app:
    image: tscampos/rotten-potatoes:v3
    build:
     dockerfile: dockerfile
     context: ./ 
    depends_on:
    - mongo
    ports:
    - 5000:5000

  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGODB_DB: admin
      MONGODB_HOST: localhost
      MONGODB_PORT: '27017'
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongo:27017/